#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension albert.TabOut
code --install-extension Angular.ng-template
code --install-extension bierner.markdown-mermaid
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hashicorp.terraform
code --install-extension henoc.svgeditor
code --install-extension HungVo.htext
code --install-extension janisdd.vscode-edit-csv
code --install-extension jock.svg
code --install-extension johnpapa.Angular2
code --install-extension manuth.markdown-converter
code --install-extension marp-team.marp-vscode
code --install-extension mattlott.copy-github-url
code --install-extension mikestead.dotenv
code --install-extension mindaro-dev.file-downloader
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nrwl.angular-console
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension pucelle.vscode-css-navigation
code --install-extension quicktype.quicktype
code --install-extension recoiljs-snippets.recoiljs-snippets
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension scala-lang.scala
code --install-extension shakram02.bash-beautify
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension unifiedjs.vscode-mdx
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-lombok
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension william-voyek.vscode-nginx
code --install-extension xyc.vscode-mdx-preview
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
