name: Docs to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-to-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RESUME_PAT }}

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: docs/pdf
          images_dir: docs/images
          image_import: ./images
          build_html: false

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: regenerate resume PDF"
          file_pattern: docs/pdf/*.pdf

      - name: Generate release tag
        id: tag
        run: |
          TAG=$(TZ="America/Chicago" date +"%y.%m.%d.%H%M")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          files: ${{ github.workspace }}/docs/pdf/*.pdf
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.RESUME_PAT }}
